//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Copies files from rom (or simulated rom in case of emulator) to ${SYSDRIVE} to make
// it easier to manually run tests from ${SYSDRIVE}
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS	MkDir		${SYSDRIVE}\ecom\
RUN_UTILS	CopyFile	z:\ecom\t_ecom.script	${SYSDRIVE}\ecom\t_ecom.script
RUN_UTILS	MakeReadWrite	${SYSDRIVE}\ecom\t_ecom.script

RUN_UTILS	CopyFile	z:\ecom\t_ecom.tcs	${SYSDRIVE}\ecom\t_ecom.tcs
RUN_UTILS	MakeReadWrite	${SYSDRIVE}\ecom\t_ecom.tcs

RUN_SCRIPT	z:\ecom\setup-SYSLIB-ECOM-PublicAPI.script
