//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tmkfifo
LOAD_SUITE tmkfifo

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest1 \tstdapis\tmkfifo.ini Section_IntgTest1
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest2 \tstdapis\tmkfifo.ini Section_IntgTest2
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNULL \tstdapis\tmkfifo.ini Section_FifoCreateNULL
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateInSystemDir
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNameTooLong
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest3 \tstdapis\tmkfifo.ini Section_IntgTest3
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNonExistantDir
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_1
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest5 \tstdapis\tmkfifo.ini Section_IntgTest5
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_2
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest6 \tstdapis\tmkfifo.ini Section_IntgTest6
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_3
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest7 \tstdapis\tmkfifo.ini Section_IntgTest7
RUN_TEST_STEP !Result=0 5 tmkfifo  TMkfifoReaderWriter \tstdapis\tmkfifo.ini Section_TMkfifoReaderWriter
RUN_TEST_STEP !Result=0 5 tmkfifo  TMkfifoReaderWriter1 \tstdapis\tmkfifo.ini Section_TMkfifoReaderWriter1
