//
// Copyright (c) 2006-2008 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tselect
LOAD_SUITE tselect

CONSECUTIVE

RUN_TEST_STEP !Result=0 -1 tselect TestTimeout 
RUN_TEST_STEP !Result=0 5 tselect TestReadFileDesc 
RUN_TEST_STEP !Result=0 5 tselect TestWriteFileDesc 
RUN_TEST_STEP !Result=0 5 tselect TestReadWriteFileDesc 
RUN_TEST_STEP !Result=0 5 tselect TestPipeReadDesc 
RUN_TEST_STEP !Result=0 5 tselect TestPipeReadDesc1
RUN_TEST_STEP !Result=0 5 tselect TestPipeWriteDesc 
RUN_TEST_STEP !Result=0 5 tselect TestSocketDesc 
RUN_TEST_STEP !Result=0 5 tselect TestSocketDesc2 
RUN_TEST_STEP !Result=0 5 tselect TestMultipleDesc 
