//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

RUN_UTILS MkDir		${SYSDRIVE}\sip\sipprofile\


RUN_UTILS CopyFile	z:\sip\sipprofile\sip_profile-ne.script 				${SYSDRIVE}\sip\sipprofile\sip_profile-ne.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\sip_profile-ne.script


RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipmanagedprofile-ne.script 				${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofile-ne.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofile-ne.script

RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipmanagedprofile-ne.ini 				${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofile-ne.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofile-ne.ini


RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipprofileregistry-ne.script 				${SYSDRIVE}\sip\sipprofile\t_csipprofileregistry-ne.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipprofileregistry-ne.script

RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipprofileregistry-ne.ini 				${SYSDRIVE}\sip\sipprofile\t_csipprofileregistry-ne.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipprofileregistry-ne.ini


RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipmanagedprofileregistry-ne.script 				${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofileregistry-ne.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofileregistry-ne.script

RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipmanagedprofileregistry-ne.ini 				${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofileregistry-ne.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipmanagedprofileregistry-ne.ini


RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipprofile-ne.script 				${SYSDRIVE}\sip\sipprofile\t_csipprofile-ne.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipprofile-ne.script

RUN_UTILS CopyFile	z:\sip\sipprofile\t_csipprofile-ne.ini 				${SYSDRIVE}\sip\sipprofile\t_csipprofile-ne.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sipprofile\t_csipprofile-ne.ini
