//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
//
// Runs all negative tests in the SIP Profile area
///////////////////////////////////////////////////////////////////////////////
RUN_SCRIPT	${SYSDRIVE}\SIP\sipprofile\t_csipmanagedprofile-ne.script
RUN_SCRIPT	${SYSDRIVE}\SIP\sipprofile\t_csipprofileregistry-ne.script
RUN_SCRIPT	${SYSDRIVE}\SIP\sipprofile\t_csipmanagedprofileregistry-ne.script
RUN_SCRIPT	${SYSDRIVE}\SIP\sipprofile\t_csipprofile-ne.script