//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
//! @file
//! @SYMTestSuiteName		t-csipmanagedprofileregistry-ne
//! @SYMScriptTestEnvironment	This test script requires a basic ROM. 
//! @SYMScriptAutomation	The test suites are fully automated using TestDriver and Testexecute


LOAD_SUITE	t_sipprofileapi
DELAY		2000