//
// Copyright (c) 2007 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tcomport
LOAD_SUITE tcomport

CONSECUTIVE

RUN_TEST_STEP !Result=0 10 tcomport test_printf_COM 
//to be run manually
//RUN_TEST_STEP !Result=0 10 tcomport test_scanf_COM 

