//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
// Copyright (c) 2006 Symbian Software Ltd.  All rights reserved.
//
CONSECUTIVE
//START_TESTCASE OE-001
//RUN_PROGRAM -1 setcap.exe tioccomcap.exe 000000  tioccom_cap1.exe
//LOAD_SUITE tioccom_cap1
//RUN_TEST_STEP  !Result=13 tioccom_cap1 ioctlsocket
//END_TESTCASE OE-001


START_TESTCASE OE-002
RUN_PROGRAM -1 setcap.exe tioccomcap.exe 000800  tioccom_cap2.exe
LOAD_SUITE tioccom_cap2
RUN_TEST_STEP  tioccom_cap2 ioctlsocket
END_TESTCASE OE-002

