//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tcondbroadcast
LOAD_SUITE tcondbroadcast

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond452
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond453
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond454
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond455
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond456
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond457
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond458
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond675
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond676
RUN_TEST_STEP !Result=0 5 tcondbroadcast TestCond677


