//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// setup-BT-USER-SOCK-PublicApi.script
//
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Copies files from rom (or simulated rom in case of emulator) to ${SYSDRIVE} to make
// it easier to manually run tests from ${SYSDRIVE}
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS MkDir		${SYSDRIVE}\bluetooth\

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.script		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.script

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.tcs		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.script	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.script

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.tcs	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.script		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.tcs		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.script	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.script

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.tcs	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.script	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.tcs	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.ini		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.ini

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.ini		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.ini		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Active-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.ini		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.ini		${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Passive-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\UccControlChannelConfig.ini			${SYSDRIVE}\UccControlChannelConfig.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\UccControlChannelConfig.ini
