//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tglob 
LOAD_SUITE tglob 

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tglob globappend 
RUN_TEST_STEP !Result=0 5 tglob globbrace 
RUN_TEST_STEP !Result=0 5 tglob globdooffs
RUN_TEST_STEP !Result=0 5 tglob globmark 
RUN_TEST_STEP !Result=0 5 tglob globnocheck 
RUN_TEST_STEP !Result=0 5 tglob globnosort
//RUN_TEST_STEP !Result=0 5 tglob globtilde
