//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-2008 Symbian Software Ltd. All rights reserved.
//
// Copy scripts and test data to system drive
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS MkDir		${SYSDRIVE}\graphics\

//	copy script files
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-PublicApi.script	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.script

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-PublicApi.tcs	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.tcs

RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-FbsBitmap-PublicApi.script
RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-FbsColor256BitmapUtil-PublicApi.script
RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-FbsFont-PublicApi.script
RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-FbsSession-PublicApi.script
RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-FbsTypefaceStore-PublicApi.script
RUN_SCRIPT		z:\graphics\setup-GRAPHICS-FBSERV-BitmapUtil-PublicApi.script
