//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Copies BitmapUtil files from rom (or simulated rom in case of emulator) to system drive
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS MkDir		${SYSDRIVE}\graphics\

// copy script files

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-PublicApi.script		${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.script

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-PublicApi.tcs		${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-PublicApi.tcs

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.script	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.script

RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.tcs	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.tcs

// copy ini data file
RUN_UTILS CopyFile	z:\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.ini	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\graphics\GRAPHICS-FBSERV-BitmapUtil-PublicApi.ini
