//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsemwait
LOAD_SUITE tsemwait

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tsemwait TestSem286
RUN_TEST_STEP !Result=0 5 tsemwait TestSem287
RUN_TEST_STEP !Result=0 5 tsemwait TestSem288
RUN_TEST_STEP !Result=0 5 tsemwait TestSem290

