//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName               t_csipservertransaction
//! @SYMScriptTestEnvironment       This test script requires a basic ROM. An Echo server listening on ports 10007 and 10008.
//                                  The communicaion to the server is established using the default connection.
//                                  The supplied commsdat is set up to use NTRAS on Emulator as well as on H/W.
//! @SYMScriptAutomation            The test suites are fully automated using TestDriver and Testexecute


LOAD_SUITE   t_sipclientapi
DELAY     2000

START_TESTCASE              receive-sip-request-slave-0001
//! @SYMTestCaseID          receive-sip-request-slave-0001
//! @SYMAuthor              Jason Lin
//! @SYMCreationDate        08/03/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        CREATE_OBJECT   CSIPCSeqHeader                cseqheader
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         siprequestelements            CSeqHeader          receive-sip-request-slave-0001-CSeqHeader_Command24
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0001

START_TESTCASE              receive-sip-request-slave-0002
//! @SYMTestCaseID          receive-sip-request-slave-0002
//! @SYMAuthor              Jasper Li
//! @SYMCreationDate        08/03/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        Dummy receiver for CSIPConnection::SendRequestL object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0002

START_TESTCASE              receive-sip-request-slave-0003
//! @SYMTestCaseID          receive-sip-request-slave-0003
//! @SYMAuthor              Jasper Li
//! @SYMCreationDate        08/03/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        Dummy receiver for CSIPConnection::SendRequestL object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0003

START_TESTCASE              receive-sip-request-slave-0004
//! @SYMTestCaseID          receive-sip-request-slave-0004
//! @SYMAuthor              Jasper Li
//! @SYMCreationDate        08/03/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        Dummy receiver for CSIPConnection::SendRequestL object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0004

START_TESTCASE              receive-sip-request-slave-0005
//! @SYMTestCaseID          receive-sip-request-slave-0005
//! @SYMAuthor              Simon Zhang
//! @SYMCreationDate        09/04/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPDialog                    sipdialog
        COMMAND         sip                           NewL                receive-sip-request-slave-0005-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0005-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0005-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0005-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0005-SaveL_command16
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0005-DefaultProfileL_command17
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0005-EnableL_command18
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0005-NewL_command19
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0005-WaitForIncomingReq_command20
        OUTSTANDING
        COMMAND         sipconnection                 WaitForInviteCanceled  receive-sip-request-slave-0005-WaitForInviteCanceled_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0005-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0005-DestroyL_command23
        OUTSTANDING
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0005

START_TESTCASE              receive-sip-request-slave-0006
//! @SYMTestCaseID          receive-sip-request-slave-0006
//! @SYMAuthor              Simon Zhang
//! @SYMCreationDate        09/14/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        Dummy receiver for CSIPConnection::SendRequestL object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0006

START_TESTCASE              receive-sip-request-slave-0007
//! @SYMTestCaseID          receive-sip-request-slave-0007
//! @SYMAuthor              Simon Zhang
//! @SYMCreationDate        09/14/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        Dummy receiver for CSIPConnection::SendRequestL object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0001-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0001-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0001-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0001-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0001-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0001-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0001-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0001-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0001-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0001-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0001-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0001-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0001-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0001-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0001-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0007

START_TESTCASE              receive-sip-request-slave-0101
//! @SYMTestCaseID          receive-sip-request-slave-0101
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements1
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements2
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        CREATE_OBJECT   CSIPMessageElements           messageelements
        CREATE_OBJECT   CSIPContentTypeHeader         contenttypeheader
        CREATE_OBJECT   CSdpOriginField               sdporiginfield
        CREATE_OBJECT   CSdpConnectionField           sdpconnectionfield
        CREATE_OBJECT   CSdpMediaField                sdpmediafield
        CREATE_OBJECT   CSdpDocument                  sdpdocument
        CREATE_OBJECT   SdpCodecStringPool            sdpcodecstringpool
        CREATE_OBJECT   CSIPDialog                    sipdialog
        COMMAND         sip                           NewL                receive-sip-request-slave-0101-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0101-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0101-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0101-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0101-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0101-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0101-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0101-NewL_command16
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0101-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewL                receive-sip-request-slave-0101-NewL_command18
        COMMAND         sipresponseelements1          NewL                receive-sip-request-slave-0101-NewL_command19
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0101-SendResponseL_command20
        COMMAND         contenttypeheader             NewL                receive-sip-request-slave-0101-NewL_command21
        COMMAND         sdpcodecstringpool            OpenL
        COMMAND         sdporiginfield                NewL                receive-sip-request-slave-0101-NewL_command22
        COMMAND         sdpconnectionfield            NewL                receive-sip-request-slave-0101-NewL_command23
        COMMAND         sdpmediafield                 NewL                receive-sip-request-slave-0101-NewL_command24
        COMMAND         sdpdocument                   NewL
        COMMAND         sdpdocument                   SetOriginField      receive-sip-request-slave-0101-SetOriginField_command25
        COMMAND         sdpdocument                   SetSessionNameL     receive-sip-request-slave-0101-SetSessionNameL_command26
        COMMAND         sdpdocument                   SetConnectionField  receive-sip-request-slave-0101-SetConnectionField_command27
        COMMAND         sdpdocument                   MediaFields_Append  receive-sip-request-slave-0101-MediaFields_Append_command28
        COMMAND         sdpdocument                   EncodeL
        COMMAND         sipresponseelements2          NewL                receive-sip-request-slave-0101-NewL_command29
        COMMAND         sipresponseelements2          MessageElements     receive-sip-request-slave-0101-MessageElements_command30
        COMMAND         messageelements               SetContentL         receive-sip-request-slave-0101-SetContentL_command31
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0101-SendResponseL_command32
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0101-WaitForIncomingReq_command33
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0101-Disable_command34
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0101-DestroyL_command35
        OUTSTANDING
        COMMAND         sipresponseelements1           ~
        COMMAND         sipresponseelements2           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sdpdocument                   ~
        COMMAND         sdpconnectionfield            ~
        COMMAND         sdpmediafield                 ~
        COMMAND         sdporiginfield                ~
        COMMAND         contenttypeheader             ~
        COMMAND         sdpcodecstringpool            Close
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0101

DELAY     150000

START_TESTCASE              receive-sip-request-slave-0102
//! @SYMTestCaseID          receive-sip-request-slave-0102
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request(INVITE).
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response(180) to server.
//!                         20.Send response(200) to server.
//!                         21.Wait for the incoming request(PRACK).
//!                         22.Send response(200) to server.
//!                         23.Disable the profile.
//!                         24.Remove the SIP profile from the persistent storage.
//!                         25.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Receive PRACK request successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements1
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements2
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        CREATE_OBJECT   CSIPMessageElements           messageelements
        CREATE_OBJECT   CSIPContentTypeHeader         contenttypeheader
        CREATE_OBJECT   CSdpOriginField               sdporiginfield
        CREATE_OBJECT   CSdpConnectionField           sdpconnectionfield
        CREATE_OBJECT   CSdpMediaField                sdpmediafield
        CREATE_OBJECT   CSdpDocument                  sdpdocument
        CREATE_OBJECT   SdpCodecStringPool            sdpcodecstringpool
        CREATE_OBJECT   CSIPDialog                    sipdialog
        COMMAND         sip                           NewL                receive-sip-request-slave-0102-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0102-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0102-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0102-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0102-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0102-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0102-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0102-NewL_command16
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0102-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewLC                receive-sip-request-slave-0102-NewLC_command18
        COMMAND         sipresponseelements1          NewL                receive-sip-request-slave-0102-NewL_command19
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0102-SendResponseL_command20
        COMMAND         contenttypeheader             NewL                receive-sip-request-slave-0102-NewL_command21
        COMMAND         sdpcodecstringpool            OpenL
        COMMAND         sdporiginfield                NewL                receive-sip-request-slave-0102-NewL_command22
        COMMAND         sdpconnectionfield            NewL                receive-sip-request-slave-0102-NewL_command23
        COMMAND         sdpmediafield                 NewL                receive-sip-request-slave-0102-NewL_command24
        COMMAND         sdpdocument                   NewL
        COMMAND         sdpdocument                   SetOriginField      receive-sip-request-slave-0102-SetOriginField_command25
        COMMAND         sdpdocument                   SetSessionNameL     receive-sip-request-slave-0102-SetSessionNameL_command26
        COMMAND         sdpdocument                   SetConnectionField  receive-sip-request-slave-0102-SetConnectionField_command27
        COMMAND         sdpdocument                   MediaFields_Append  receive-sip-request-slave-0102-MediaFields_Append_command28
        COMMAND         sdpdocument                   EncodeL
        COMMAND         sipresponseelements2          NewL                receive-sip-request-slave-0102-NewL_command29
        COMMAND         sipresponseelements2          MessageElements     receive-sip-request-slave-0102-MessageElements_command30
        COMMAND         messageelements               SetContentL         receive-sip-request-slave-0102-SetContentL_command31
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0102-SendResponseL_command32
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0102-WaitForIncomingReq_command33
        OUTSTANDING
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0102-SendResponseL_command34
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0102-Disable_command35
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0102-DestroyL_command36
        OUTSTANDING
        COMMAND         messageelements              ~
        COMMAND         sipresponseelements1           ~
        COMMAND         sipresponseelements2           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sdpdocument                   ~
        COMMAND         sdpconnectionfield            ~
        COMMAND         sdpmediafield                 ~
        COMMAND         sdporiginfield                ~
        COMMAND         contenttypeheader             ~
        COMMAND         sdpcodecstringpool            Close
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0102

DELAY     150000

START_TESTCASE              receive-sip-request-slave-0103
//! @SYMTestCaseID          receive-sip-request-slave-0103
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request(INVITE).
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response(180) to server.
//!                         20.Send response(200) to server.
//!                         21.Wait for the incoming request(UPDATE).
//!                         22.Send response(200) to server.
//!                         23.Disable the profile.
//!                         24.Remove the SIP profile from the persistent storage.
//!                         25.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Receive UPDATE request successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements1
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements2
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        CREATE_OBJECT   CSIPMessageElements           messageelements
        CREATE_OBJECT   CSIPContentTypeHeader         contenttypeheader
        CREATE_OBJECT   CSdpOriginField               sdporiginfield
        CREATE_OBJECT   CSdpConnectionField           sdpconnectionfield
        CREATE_OBJECT   CSdpMediaField                sdpmediafield
        CREATE_OBJECT   CSdpDocument                  sdpdocument
        CREATE_OBJECT   SdpCodecStringPool            sdpcodecstringpool
        CREATE_OBJECT   CSIPDialog                    sipdialog
        COMMAND         sip                           NewL                receive-sip-request-slave-0103-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0103-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0103-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0103-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0103-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0103-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0103-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0103-NewL_command16
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0103-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewL                receive-sip-request-slave-0103-NewL_command18
        COMMAND         sipresponseelements1          NewL                receive-sip-request-slave-0103-NewL_command19
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0103-SendResponseL_command20
        COMMAND         contenttypeheader             NewL                receive-sip-request-slave-0103-NewL_command21
        COMMAND         sdpcodecstringpool            OpenL
        COMMAND         sdporiginfield                NewL                receive-sip-request-slave-0103-NewL_command22
        COMMAND         sdpconnectionfield            NewL                receive-sip-request-slave-0103-NewL_command23
        COMMAND         sdpmediafield                 NewL                receive-sip-request-slave-0103-NewL_command24
        COMMAND         sdpdocument                   NewL
        COMMAND         sdpdocument                   SetOriginField      receive-sip-request-slave-0103-SetOriginField_command25
        COMMAND         sdpdocument                   SetSessionNameL     receive-sip-request-slave-0103-SetSessionNameL_command26
        COMMAND         sdpdocument                   SetConnectionField  receive-sip-request-slave-0103-SetConnectionField_command27
        COMMAND         sdpdocument                   MediaFields_Append  receive-sip-request-slave-0103-MediaFields_Append_command28
        COMMAND         sdpdocument                   EncodeL
        COMMAND         sipresponseelements2          NewL                receive-sip-request-slave-0103-NewL_command29
        COMMAND         sipresponseelements2          MessageElements     receive-sip-request-slave-0103-MessageElements_command30
        COMMAND         messageelements               SetContentL         receive-sip-request-slave-0103-SetContentL_command31
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0103-SendResponseL_command32
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0103-WaitForIncomingReq_command33
        OUTSTANDING
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0103-SendResponseL_command34
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0103-Disable_command35
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0103-DestroyL_command36
        OUTSTANDING
        COMMAND         messageelements              ~        
        COMMAND         sipresponseelements1           ~
        COMMAND         sipresponseelements2           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sdpdocument                   ~
        COMMAND         sdpconnectionfield            ~
        COMMAND         sdpmediafield                 ~
        COMMAND         sdporiginfield                ~
        COMMAND         contenttypeheader             ~
        COMMAND         sdpcodecstringpool            Close
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0103

DELAY     150000

START_TESTCASE              receive-sip-request-slave-0104
//! @SYMTestCaseID          receive-sip-request-slave-0104
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request(INVITE).
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response(180) to server.
//!                         20.Send response(200) to server.
//!                         21.Wait for the incoming request(BYE).
//!                         22.Send response(200) to server.
//!                         23.Disable the profile.
//!                         24.Remove the SIP profile from the persistent storage.
//!                         25.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Receive BYE request successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements1
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements2
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        CREATE_OBJECT   CSIPMessageElements           messageelements
        CREATE_OBJECT   CSIPContentTypeHeader         contenttypeheader
        CREATE_OBJECT   CSdpOriginField               sdporiginfield
        CREATE_OBJECT   CSdpConnectionField           sdpconnectionfield
        CREATE_OBJECT   CSdpMediaField                sdpmediafield
        CREATE_OBJECT   CSdpDocument                  sdpdocument
        CREATE_OBJECT   SdpCodecStringPool            sdpcodecstringpool
        CREATE_OBJECT   CSIPDialog                    sipdialog
        COMMAND         sip                           NewL                receive-sip-request-slave-0104-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0104-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0104-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0104-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0104-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0104-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0104-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0104-NewL_command16
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0104-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewL                receive-sip-request-slave-0104-NewL_command18
        COMMAND         sipresponseelements1          NewL                receive-sip-request-slave-0104-NewL_command19
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0104-SendResponseL_command20
        COMMAND         contenttypeheader             NewL                receive-sip-request-slave-0104-NewL_command21
        COMMAND         sdpcodecstringpool            OpenL
        COMMAND         sdporiginfield                NewL                receive-sip-request-slave-0104-NewL_command22
        COMMAND         sdpconnectionfield            NewL                receive-sip-request-slave-0104-NewL_command23
        COMMAND         sdpmediafield                 NewL                receive-sip-request-slave-0104-NewL_command24
        COMMAND         sdpdocument                   NewL
        COMMAND         sdpdocument                   SetOriginField      receive-sip-request-slave-0104-SetOriginField_command25
        COMMAND         sdpdocument                   SetSessionNameL     receive-sip-request-slave-0104-SetSessionNameL_command26
        COMMAND         sdpdocument                   SetConnectionField  receive-sip-request-slave-0104-SetConnectionField_command27
        COMMAND         sdpdocument                   MediaFields_Append  receive-sip-request-slave-0104-MediaFields_Append_command28
        COMMAND         sdpdocument                   EncodeL
        COMMAND         sipresponseelements2          NewL                receive-sip-request-slave-0104-NewL_command29
        COMMAND         sipresponseelements2          MessageElements     receive-sip-request-slave-0104-MessageElements_command30
        COMMAND         messageelements               SetContentL         receive-sip-request-slave-0104-SetContentL_command31
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0104-SendResponseL_command32
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0104-WaitForIncomingReq_command33
        OUTSTANDING
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0104-SendResponseL_command34
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0104-Disable_command35
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0104-DestroyL_command36
        OUTSTANDING
        COMMAND         messageelements              ~
        COMMAND         sipresponseelements1           ~
        COMMAND         sipresponseelements2           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sdpdocument                   ~
        COMMAND         sdpconnectionfield            ~
        COMMAND         sdpmediafield                 ~
        COMMAND         sdporiginfield                ~
        COMMAND         contenttypeheader             ~
        COMMAND         sdpcodecstringpool            Close
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0104

DELAY     150000

START_TESTCASE              receive-sip-request-slave-0105
//! @SYMTestCaseID          receive-sip-request-slave-0105
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request(INVITE).
//!                         18.Create a CSIPInviteDialogAssoc object
//!                         19.Disable the profile.
//!                         20.Remove the SIP profile from the persistent storage.
//!                         21.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Invite request successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        COMMAND         sip                           NewL                receive-sip-request-slave-0105-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0105-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0105-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0105-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0105-SaveL_command16
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0105-DefaultProfileL_command17
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0105-EnableL_command18
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0105-NewL_command19
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0105-WaitForIncomingReq_command20
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewL                receive-sip-request-slave-0105-NewL_command21
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0105-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0105-DestroyL_command23
        OUTSTANDING
        COMMAND         sipservertransaction          ~
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0105


START_TESTCASE              receive-sip-request-slave-0106
//! @SYMTestCaseID          receive-sip-request-slave-0106
//! @SYMAuthor              Wekey Weng
//! @SYMCreationDate        08/17/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters.  
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request(INVITE).
//!                         18.Create a CSIPInviteDialogAssoc object
//!                         19.Disable the profile.
//!                         20.Remove the SIP profile from the persistent storage.
//!                         21.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Invite request successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    300 t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPInviteDialogAssoc         sipinvitedialogassoc        
        COMMAND         sip                           NewL                receive-sip-request-slave-0106-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0106-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0106-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0106-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0106-SaveL_command16
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0106-DefaultProfileL_command17
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0106-EnableL_command18
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0106-NewL_command19
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0106-WaitForIncomingReq_command20
        OUTSTANDING
        COMMAND         sipinvitedialogassoc          NewLC               receive-sip-request-slave-0106-NewLC_command21
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0106-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0106-DestroyL_command23
        OUTSTANDING
        COMMAND         sipservertransaction          ~
        COMMAND         sipinvitedialogassoc          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE            receive-sip-request-slave-0106

START_TESTCASE              receive-sip-request-slave-0107
//! @SYMTestCaseID          receive-sip-request-slave-0107
//! @SYMAuthor              Jason Lin
//! @SYMCreationDate        08/03/2009
//! @SYMAPI                 CSIPConnection::
//! @SYMTestCaseDesc        CSIPConnection object.
//! @SYMTestActions         1. Create a CSIP object.
//!                         2. Create a CSIPProfileRegistry object with the CSIP object.
//!                         3. Create a CSIPManagedProfileRegistry object.
//!                         4. Instantiate a new profile with default values for given type. 
//!                         5. Set profile KSIPAccessPointId parameter. 
//!                         6. Set profile KSIPUserAor parameter. 
//!                         7. Set profile KSIPProviderName parameter. 
//!                         8. Set profile KSIPSigComp parameter. 
//!                         9. Set profile KSIPAutoRegistration parameter. 
//!                         10.Set profile KSIPDefaultProfile parameter. 
//!                         11.Set profile KSIPSecurityNegotiation parameter. 
//!                         12.Set profile KSIPRegistrar and KSIPServerAddress parameters. 	
//!                         13.Save new profile to the persistent storage.
//!                         14.Get the default profile.
//!                         15.Enable the  profile.
//!                         16.Create a CSIPConnection object.
//!                         17.Wait for the incoming request.
//!                         18.Create a CSIPResponseElements object.
//!                         19.Send response to server.
//!                         20.Disable the profile.
//!                         21.Remove the SIP profile from the persistent storage.
//!                         22.Destroy all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The profile is cloned successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    200  t_sipclientapi            \SIP\sipclient\receive-sip-request-slave.ini
        CREATE_OBJECT   CSIP                          sip
        CREATE_OBJECT   CSIPProfileRegistry           sipprofileregistry
        CREATE_OBJECT   CSIPManagedProfileRegistry    sipmanagedprofileregistry
        CREATE_OBJECT   CSIPManagedProfile            sipmanagedprofile
        CREATE_OBJECT   CSIPProfile                   sipprofile
        CREATE_OBJECT   CSIPConnection                sipconnection
        CREATE_OBJECT   CSIPServerTransaction         sipservertransaction
        CREATE_OBJECT   CSIPResponseElements          sipresponseelements
        CREATE_OBJECT   CSIPRequestElements           siprequestelements
        COMMAND         sip                           NewL                receive-sip-request-slave-0107-NewL_command01
        COMMAND         sipprofileregistry            NewL                receive-sip-request-slave-0107-NewL_command02
        COMMAND         sipmanagedprofileregistry     NewL
        COMMAND         sipmanagedprofileregistry     CreateL             receive-sip-request-slave-0107-CreateL_command04
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command05
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command06
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command07
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command08
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command09
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command10
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command11
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command12
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command13
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command14
        COMMAND         sipmanagedprofile             SetParameter        receive-sip-request-slave-0107-SetParameter_command15
        COMMAND         sipmanagedprofileregistry     SaveL               receive-sip-request-slave-0107-SaveL_command13
        OUTSTANDING
        COMMAND         sipprofileregistry            DefaultProfileL     receive-sip-request-slave-0107-DefaultProfileL_command14
        COMMAND         sipprofileregistry            EnableL             receive-sip-request-slave-0107-EnableL_command15
        OUTSTANDING
        COMMAND         sipconnection                 NewL                receive-sip-request-slave-0107-NewL_command16
        OUTSTANDING
        COMMAND         sipconnection                 WaitForIncomingRequest  receive-sip-request-slave-0107-WaitForIncomingReq_command17
        OUTSTANDING
        COMMAND         sipservertransaction          RequestElements     receive-sip-request-slave-0107-RequestElements_command18  
        COMMAND         sipservertransaction          ResponseAllowed     receive-sip-request-slave-0107-ResponseAllowed_command19
        COMMAND         sipresponseelements           NewL                receive-sip-request-slave-0107-NewL_command20
        COMMAND         sipservertransaction          SendResponseL       receive-sip-request-slave-0107-SendResponseL_command21
        OUTSTANDING
        COMMAND         sipprofileregistry            Disable             receive-sip-request-slave-0107-Disable_command22
        OUTSTANDING
        COMMAND         sipmanagedprofileregistry     DestroyL            receive-sip-request-slave-0107-DestroyL_command23
        OUTSTANDING
        COMMAND         siprequestelements            ~
        COMMAND         sipresponseelements           ~
        COMMAND         sipservertransaction          ~
        COMMAND         sipconnection                 ~
        COMMAND         sipprofile                    ~
        COMMAND         sipmanagedprofile             ~
        COMMAND         sipmanagedprofileregistry     ~
        COMMAND         sipprofileregistry            ~
        COMMAND         sip                           ~
    END_TEST_BLOCK
END_TESTCASE                receive-sip-request-slave-0107
