//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tcondwait
LOAD_SUITE tcondwait

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tcondwait TestCond405
RUN_TEST_STEP !Result=0 5 tcondwait TestCond408
RUN_TEST_STEP !Result=0 5 tcondwait TestCond409
RUN_TEST_STEP !Result=0 5 tcondwait TestCond410
RUN_TEST_STEP !Result=0 5 tcondwait TestCond411
RUN_TEST_STEP !Result=0 5 tcondwait TestCond413
RUN_TEST_STEP !Result=0 5 tcondwait TestCond414
RUN_TEST_STEP !Result=0 5 tcondwait TestCond415
// RUN_TEST_STEP !Result=0 5 tcondwait TestCond681
// RUN_TEST_STEP !Result=0 5 tcondwait TestCond682
