//
// Copyright (c) 2006-2007 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tldouble_blr
LOAD_SUITE tldouble_blr

CONSECUTIVE
RUN_TEST_STEP !Result=0 5 tldouble_blr  erfcl_test \tstdapis\tldouble_blr.ini Section_erfcl_test_10
RUN_TEST_STEP !Result=0 5 tldouble_blr  expl_test \tstdapis\tldouble_blr.ini Section_expl_test_3
RUN_TEST_STEP !Result=0 5 tldouble_blr  expl_test \tstdapis\tldouble_blr.ini Section_expl_test_4
RUN_TEST_STEP !Result=0 5 tldouble_blr  expl_test \tstdapis\tldouble_blr.ini Section_expl_test_8
RUN_TEST_STEP !Result=0 5 tldouble_blr  expl_test \tstdapis\tldouble_blr.ini Section_expl_test_10

RUN_TEST_STEP !Result=0 5 tldouble_blr  j0l_test \tstdapis\tldouble_blr.ini Section_j0l_test_9
RUN_TEST_STEP !Result=0 5 tldouble_blr  j1l_test \tstdapis\tldouble_blr.ini Section_j1l_test_11

RUN_TEST_STEP !Result=0 5 tldouble_blr  acosl_test \tstdapis\tldouble_blr.ini Section_acosl_test_8
RUN_TEST_STEP !Result=0 5 tldouble_blr  acosl_test \tstdapis\tldouble_blr.ini Section_acosl_test_12
RUN_TEST_STEP !Result=0 5 tldouble_blr  acosl_test \tstdapis\tldouble_blr.ini Section_acosl_test_14