//
// Copyright (c) 2006-2008 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tifioctls
LOAD_SUITE tifioctls

CONSECUTIVE

RUN_TEST_STEP !Result=0 50 tifioctls ExampleL \tstdapis\tifioctls.ini SectionExampleL 
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_1
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_2
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_3
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_4
RUN_TEST_STEP !Result=0 50 tifioctls ChooseInterface \tstdapis\tifioctls.ini SectionChooseInterface_1
RUN_TEST_STEP !Result=0 50 tifioctls ChooseActiveInterface \tstdapis\tifioctls.ini SectionChooseActiveInterface
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameIndex
RUN_TEST_STEP !Result=0 50 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_1
RUN_TEST_STEP !Result=0 50 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_2
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameToIndex \tstdapis\tifioctls.ini SectionTestIfNameToIndex_1
RUN_TEST_STEP !Result=0 50 tifioctls TestSiocGIfIndex \tstdapis\tifioctls.ini SectionTestSiocGIfIndex
RUN_TEST_STEP !Result=0 100 tifioctls CreateManyActiveInterfaces \tstdapis\tifioctls.ini SectionCreateManyActiveInterfaces
//RUN_TEST_STEP !Result=0 50 tifioctls ChooseInterface \tstdapis\tifioctls.ini SectionChooseInterface_2
RUN_TEST_STEP !Result=0 50 tifioctls ConnectToIpUsingConnection \tstdapis\tifioctls.ini SectionConnectToIpUsingConnection
RUN_TEST_STEP !Result=0 50 tifioctls SendtoIpUsingConnection \tstdapis\tifioctls.ini SectionConnectToIpUsingConnection
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameToIndex \tstdapis\tifioctls.ini SectionTestIfNameToIndex_2
// To cover CTtyDesc::IoctlCompletion in backend
RUN_TEST_STEP !Result=0 10 tifioctls ioctltest
// To cover CTtyDesc::MapCodeAndEcho in backend this would be a manual test
//as we cannot make a key press input for cttydesc console(stdout)
//RUN_TEST_STEP !Result=0 10 tifioctls readtest
RUN_TEST_STEP !Result=0 50 tifioctls Testioctlfile
RUN_TEST_STEP !Result=0 50 tifioctls Testioctl1