//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tifioctls
LOAD_SUITE tifioctls

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tifioctls ConnectToUrlUsingConnection \tstdapis\tifioctls.ini SectionConnectToUrlUsingConnection
RUN_TEST_STEP !Result=0 50 tifioctls TestAddDelRoute
RUN_TEST_STEP !Result=0 50 tifioctls TestAddDelRouteNegative1
RUN_TEST_STEP !Result=0 50 tifioctls TestAddDelRouteNegative2
RUN_TEST_STEP !Result=0 50 tifioctls TestMacAddress
RUN_TEST_STEP !Result=0 50 tifioctls TestMacAddressNegative1 \tstdapis\tifioctls.ini SectionInvalidIFName
RUN_TEST_STEP !Result=0 50 tifioctls TestMacAddressNegative1 \tstdapis\tifioctls.ini SectionNullIFName
