//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
//! @file
//! @SYMTestSuiteName   t_sipcodecapi
//! @SYMScriptTestEnvironment This test script requires a basic ROM. An SIP server listening on ports 5060.
//        The communicaion to the server is established using the default connection.
//        The supplied commsdat is set up to use NTRAS on Emulator as well as on H/W.
//! @SYMScriptAutomation  The test suites are fully automated using TestDriver and Testexecute

/////////////////////////////////////////////////////////////////////
// t_csipacceptcontactheader
//
// Tests all public elements of the t_csipacceptcontactheader
// classes as a means of confidence that the APIs work as expected.
//
// The purpose is to provide a regression test suite of PublishedAll APIs for CSIPAcceptContactHeader
// The tests are fully automated.
/////////////////////////////////////////////////////////////////////

LOAD_SUITE  t_sipcodecapi
DELAY   2000

START_TESTCASE              t_csipacceptcontactheader-0001
//! @SYMTestCaseID          t_csipacceptcontactheader-0001
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::NewL() 
//! @SYMTestCaseDesc        Construct and destruct CSIPAcceptContactHeader object.
//! @SYMTestActions         1. Create a CSIP object and a CSIPAcceptContactHeader object.
//!                         2. Construct CSIP and CSIPAcceptContactHeader object.
//!                         3. Delete the CSIPAcceptContactHeader object.
//!                         4. Delete the CSIP object.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The SIP Codec can start and close successfully without causing any panic
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi                      \SIP\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIP                        sip
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        COMMAND             sip                         NewL                        t_csipacceptcontactheader-0001-NewL_Command01
        COMMAND             sipacceptcontactheader      NewL
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0001

START_TESTCASE              t_csipacceptcontactheader-0002
//! @SYMTestCaseID          t_csipacceptcontactheader-0002
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::NewLC()
//! @SYMTestCaseDesc        Constructs a CSIPAcceptContactHeader object.
//! @SYMTestActions         1. Create a CSIP object and a CSIPAcceptContactHeader object.
//!                         2. Construct CSIP, and construct CSIPAcceptContactHeader object.
//!                         3. Delete the CSIPAcceptContactHeader object.
//!                         4. Delete the CSIP object.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The SIP Codec can start and close successfully without causing any panic
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi                      \SIP\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIP                        sip
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        COMMAND             sip                         NewL                        t_csipacceptcontactheader-0002-NewL_Command01
        COMMAND             sipacceptcontactheader      NewLC
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0002

START_TESTCASE              t_csipacceptcontactheader-0003
//! @SYMTestCaseID          t_csipacceptcontactheader-0003
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::DecodeL(const TDesC8{ref})
//! @SYMTestCaseDesc        Constructs a CSIPAcceptContactHeader object from textual presentation.
//! @SYMTestActions         1. Create a CSIP object and 2 CSIPAcceptContactHeader objects.
//!                         2. Construct CSIP object.
//!                         3. Construct CSIPAcceptContactHeader objects from textual presentation.
//!                         4. Delete all objects
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The CSIPAcceptContactHeader can be decoded successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi                      \SIP\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIP                        sip
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader1
        COMMAND             sip                         NewL                        t_csipacceptcontactheader-0003-NewL_Command01
        COMMAND             sipacceptcontactheader      DecodeL                     t_csipacceptcontactheader-0003-DecodeL_Command02
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sipacceptcontactheader1     ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0003

START_TESTCASE              t_csipacceptcontactheader-0004
//! @SYMTestCaseID          t_csipacceptcontactheader-0004
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::operator ==(const CSIPAcceptContactHeader{ref})
//! @SYMTestCaseDesc        Compare 2 CSIPAcceptContactHeader objects.
//! @SYMTestActions         1. Create a CSIP object and 2 CSIPAcceptContactHeader objects.
//!                         2. Construct CSIP object.
//!                         3. Construct CSIPAcceptContactHeader objects from textual presentation.
//!                         4. Compare 2 CSIPAcceptContactHeader objects.
//!                         5. Delete all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults The returned acceptcontact is as expected.
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi                      \SIP\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIP                        sip
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader1
        COMMAND             sip                         NewL                        t_csipacceptcontactheader-0004-NewL_Command01
        COMMAND             sipacceptcontactheader      DecodeL                     t_csipacceptcontactheader-0004-DecodeL_Command02
        COMMAND             sipacceptcontactheader      ==                          t_csipacceptcontactheader-0004-==_Command03
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sipacceptcontactheader1     ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0004

START_TESTCASE              t_csipacceptcontactheader-0010
//! @SYMTestCaseID          t_csipacceptcontactheader-0010
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::Name()
//! @SYMTestCaseDesc        Gets the full name of the header.
//! @SYMTestActions         1. Create a CSIP object and a CSIPAcceptContactHeader object.
//!                         2. Construct CSIP and CSIPAcceptContactHeader object.
//!                         3. Get name of the CSIPAcceptContactHeader object.
//!                         4. Delete all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults Name() can be called successfully.
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi                      \SIP\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIP                        sip
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        COMMAND             sip                         NewL                    t_csipacceptcontactheader-0010-NewL_Command01
        COMMAND             sipacceptcontactheader      NewL
        COMMAND             sipacceptcontactheader      Name
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0010


START_TESTCASE              t_csipacceptcontactheader-0012
//! @SYMTestCaseID          t_csipacceptcontactheader-0012
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::CloneL()
//! @SYMTestCaseDesc        Creates a deep-copy of this header object.
//! @SYMTestActions         1. Create a CSIP object and 2 CSIPAcceptContactHeader objects.
//!                         2. Construct CSIP and CSIPAcceptContactHeader object.
//!                         3. Clone the CSIPAcceptContactHeader object to 2nd one and check the 2nd one is same as 1st one.
//!                         4. Delete all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults CloneL can be called successfully and the clone is same as original one.
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi             \sip\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader1
        CREATE_OBJECT       CSIP                        sip
        COMMAND             sip                         NewL                    t_csipacceptcontactheader-0012-NewL_Command01
        COMMAND             sipacceptcontactheader      NewL
        COMMAND             sipacceptcontactheader      CloneL                  t_csipacceptcontactheader-0012-CloneL_command03
        COMMAND             sipacceptcontactheader1     ==                      t_csipacceptcontactheader-0012-==_command04
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sipacceptcontactheader1     ~
        COMMAND             sip                         ~
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0012

START_TESTCASE              t_csipacceptcontactheader-0013
//! @SYMTestCaseID          t_csipacceptcontactheader-0013
//! @SYMAuthor              Felix Rao
//! @SYMCreationDate        27/10/2009
//! @SYMAPI                 CSIPAcceptContactHeader::InternalizeValueL(), CSIPAcceptContactHeader::operator ==()
//! @SYMTestCaseDesc        Constructs an instance of a CSIPAcceptContactHeader from a RReadStream.
//! @SYMTestActions         1. Create a CSIP object and 2 CSIPAcceptContactHeader objects.
//!                         2. Construct CSIP and CSIPAcceptContactHeader object.
//!                         3. Externalize 1st CSIPAcceptContactHeader object, then compare the 2 objects to check if the two are the same.
//!                         4. Delete all objects.
//! @SYMTestStatus          Implemented
//! @SYMTestPriority        High
//! @SYMTestExpectedResults A CSIPAcceptContactHeader object can be created by internalizing from a file. The new one is same as the original one which externalizes to a file.
//! @SYMTestType            CIT
    START_TEST_BLOCK    100 t_sipcodecapi             \sip\sipcodec\t_csipacceptcontactheader.ini
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader
        CREATE_OBJECT       CSIPAcceptContactHeader     sipacceptcontactheader1
        CREATE_OBJECT       CSIP                        sip
        COMMAND             sip                         NewL                        t_csipacceptcontactheader-0013-NewL_command01
        COMMAND             sipacceptcontactheader      NewL
        COMMAND             sipacceptcontactheader      ExternalizeL                t_csipacceptcontactheader-0013-ExternalizeL_command03
        COMMAND             sipacceptcontactheader1     InternalizeValueL           t_csipacceptcontactheader-0013-InternalizeValueL_command04
        COMMAND             sipacceptcontactheader1     ==                          t_csipacceptcontactheader-0013-==_command05
        COMMAND             sipacceptcontactheader      ~
        COMMAND             sipacceptcontactheader1     ~
        COMMAND             sip                         ~ 
    END_TEST_BLOCK
END_TESTCASE      t_csipacceptcontactheader-0013
