//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsemdestroy
LOAD_SUITE tsemdestroy

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem275
RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem276
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem277
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem278
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem649
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem703
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem704
//RUN_TEST_STEP !Result=0 5 tsemdestroy TestSem705

