//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Copies files from rom (or simulated rom in case of emulator) to system drive
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS	MkDir		${SYSDRIVE}\graphics\

RUN_UTILS	CopyFile	z:\graphics\t_graphics.ini	${SYSDRIVE}\graphics\t_graphics.ini
RUN_UTILS	MakeReadWrite	${SYSDRIVE}\graphics\t_graphics.ini
RUN_UTILS	CopyFile	z:\graphics\t_graphics.script	${SYSDRIVE}\graphics\t_graphics.script
RUN_UTILS	MakeReadWrite	${SYSDRIVE}\graphics\t_graphics.script
RUN_UTILS	CopyFile	z:\graphics\t_graphics.tcs	${SYSDRIVE}\graphics\t_graphics.tcs
RUN_UTILS	MakeReadWrite	${SYSDRIVE}\graphics\t_graphics.tcs

RUN_SCRIPT	z:\graphics\setup-GRAPHICS-FBSERV-PublicApi.script
