//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Runs all tests in the bluetooth area
///////////////////////////////////////////////////////////////////////////////

RUN_SCRIPT	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.script
RUN_SCRIPT	${SYSDRIVE}\bluetooth\BT-USER-SOCK-PublicApi-Unconnected.script
RUN_SCRIPT	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.script
RUN_SCRIPT	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.script
RUN_SCRIPT	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.script
