//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// Copies files from rom (or simulated rom in case of emulator) to system drive
///////////////////////////////////////////////////////////////////////////////
RUN_UTILS MkDir		${SYSDRIVE}\sip\


RUN_UTILS CopyFile	z:\sip\t_sip.ini 				${SYSDRIVE}\sip\t_sip.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\t_sip.ini

RUN_UTILS CopyFile	z:\sip\t_sip.tcs 				${SYSDRIVE}\sip\t_sip.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\t_sip.tcs

RUN_UTILS CopyFile	z:\sip\sip_all.script 				${SYSDRIVE}\sip\sip_all.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\sip\sip_all.script

RUN_SCRIPT	z:\sip\sipprofile\setup-sipprofile.script
RUN_SCRIPT	z:\sip\sipprofile\setup-sipprofile-ne.script
RUN_SCRIPT	z:\sip\sipclient\setup-sipclient.script
RUN_SCRIPT	z:\sip\sipcodec\setup-sipcodec.script
