//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsemtimedwait
LOAD_SUITE tsemtimedwait

CONSECUTIVE

//RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem291
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem292
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem303
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem304
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem305
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem306
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem701
RUN_TEST_STEP !Result=0 5 tsemtimedwait TestSem702
