//
// Copyright (c) 2006-2007 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tdouble_blr
LOAD_SUITE tdouble_blr

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  cbrt_test \tstdapis\tdouble_blr.ini Section_cbrt_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  ceil_test \tstdapis\tdouble_blr.ini Section_ceil_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  erf_test \tstdapis\tdouble_blr.ini Section_erf_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  erfc_test \tstdapis\tdouble_blr.ini Section_erfc_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp_test \tstdapis\tdouble_blr.ini Section_exp_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  exp2_test \tstdapis\tdouble_blr.ini Section_exp2_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  expm1_test \tstdapis\tdouble_blr.ini Section_expm1_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fabs_test \tstdapis\tdouble_blr.ini Section_fabs_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  ilogb_test \tstdapis\tdouble_blr.ini Section_ilogb_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  j0_test \tstdapis\tdouble_blr.ini Section_j0_test_13

RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  j1_test \tstdapis\tdouble_blr.ini Section_j1_test_10


RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  lrint_test \tstdapis\tdouble_blr.ini Section_lrint_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  llrint_test \tstdapis\tdouble_blr.ini Section_llrint_test_20

RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  log_test \tstdapis\tdouble_blr.ini Section_log_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  log10_test \tstdapis\tdouble_blr.ini Section_log10_test_12

RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  log1p_test \tstdapis\tdouble_blr.ini Section_log1p_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  logb_test \tstdapis\tdouble_blr.ini Section_logb_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  lround_test \tstdapis\tdouble_blr.ini Section_lround_test_17

RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_25
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_26
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_27
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_28
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_29
RUN_TEST_STEP !Result=0 5 tdouble_blr  llround_test \tstdapis\tdouble_blr.ini Section_llround_test_30

RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  rint_test \tstdapis\tdouble_blr.ini Section_rint_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  sqrt_test \tstdapis\tdouble_blr.ini Section_sqrt_test_14

RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  trunc_test \tstdapis\tdouble_blr.ini Section_trunc_test_17

RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  y0_test \tstdapis\tdouble_blr.ini Section_y0_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  y1_test \tstdapis\tdouble_blr.ini Section_y1_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  significand_test \tstdapis\tdouble_blr.ini Section_significand_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  significand_test \tstdapis\tdouble_blr.ini Section_significand_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  significand_test \tstdapis\tdouble_blr.ini Section_significand_test_3

RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  floor_test \tstdapis\tdouble_blr.ini Section_floor_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  nearbyint_test \tstdapis\tdouble_blr.ini Section_nearbyint_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  isinf_test \tstdapis\tdouble_blr.ini Section_isinf_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnan_test \tstdapis\tdouble_blr.ini Section_isnan_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  fdim_test \tstdapis\tdouble_blr.ini Section_fdim_test_24

RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmax_test \tstdapis\tdouble_blr.ini Section_fmax_test_25

RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmin_test \tstdapis\tdouble_blr.ini Section_fmin_test_25

RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  fmod_test \tstdapis\tdouble_blr.ini Section_fmod_test_13

RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  hypot_test \tstdapis\tdouble_blr.ini Section_hypot_test_19

RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  remainder_test \tstdapis\tdouble_blr.ini Section_remainder_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  nextafter_test \tstdapis\tdouble_blr.ini Section_nextafter_test_13

RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  nexttoward_test \tstdapis\tdouble_blr.ini Section_nexttoward_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  copysign_test \tstdapis\tdouble_blr.ini Section_copysign_test_16

RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_25
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_26
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_27
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_28
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_29
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_30
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_31
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_32
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_33
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_34
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_35
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_36
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_37
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_38
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_39
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_40
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_41
RUN_TEST_STEP !Result=0 5 tdouble_blr  jn_test \tstdapis\tdouble_blr.ini Section_jn_test_42

RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_25
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_26
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_27
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_28
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_29
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_30
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_31
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_32
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_33
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_34
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_35
RUN_TEST_STEP !Result=0 5 tdouble_blr  yn_test \tstdapis\tdouble_blr.ini Section_yn_test_36

RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_25
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_26
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_27
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_28
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_29
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_30
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_31
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_32
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_33
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_34
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_35
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_36
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_37
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_38
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalb_test \tstdapis\tdouble_blr.ini Section_scalb_test_39

RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbn_test \tstdapis\tdouble_blr.ini Section_scalbn_test_8

//RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_1
//RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_2
//RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_3
//RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_8
//RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_53

RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_56
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_57
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_58
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_59

RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_64
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_65
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_66
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_67
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_68
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_69
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_70
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_71

RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_76
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_77
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_78
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_79
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_80
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_81
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_82
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_83
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_84
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_85
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_86
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_87
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_88
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_89
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_90
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_91
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_92
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_93
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_94
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_95
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_96
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_97
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_98
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_99
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_100
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_101
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_102 
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_103
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_104
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_105
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_106
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_107
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_108
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_109

RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_120
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_121
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_122
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_123
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_124
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_125
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_126
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_127
RUN_TEST_STEP !Result=0 5 tdouble_blr  pow_test \tstdapis\tdouble_blr.ini Section_pow_test_128


RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  acos_test \tstdapis\tdouble_blr.ini Section_acos_test_13


RUN_TEST_STEP !Result=0 5 tdouble_blr  acosh_test \tstdapis\tdouble_blr.ini Section_acosh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  acosh_test \tstdapis\tdouble_blr.ini Section_acosh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  acosh_test \tstdapis\tdouble_blr.ini Section_acosh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  acosh_test \tstdapis\tdouble_blr.ini Section_acosh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  acosh_test \tstdapis\tdouble_blr.ini Section_acosh_test_5

RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  asin_test \tstdapis\tdouble_blr.ini Section_asin_test_12

RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  asinh_test \tstdapis\tdouble_blr.ini Section_asinh_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan_test \tstdapis\tdouble_blr.ini Section_atan_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  atanh_test \tstdapis\tdouble_blr.ini Section_atanh_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  Cos_test \tstdapis\tdouble_blr.ini Section_Cos_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  fpclassify_test \tstdapis\tdouble_blr.ini Section_fpclassify_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fpclassify_test \tstdapis\tdouble_blr.ini Section_fpclassify_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fpclassify_test \tstdapis\tdouble_blr.ini Section_fpclassify_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fpclassify_test \tstdapis\tdouble_blr.ini Section_fpclassify_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fpclassify_test \tstdapis\tdouble_blr.ini Section_fpclassify_test_5

RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  cosh_test \tstdapis\tdouble_blr.ini Section_cosh_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  sin_test \tstdapis\tdouble_blr.ini Section_sin_test_11

RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  sinh_test \tstdapis\tdouble_blr.ini Section_sinh_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  tan_test \tstdapis\tdouble_blr.ini Section_tan_test_7

RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  tanh_test \tstdapis\tdouble_blr.ini Section_tanh_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_19
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_20
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_21
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_22
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_23
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_24
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_25
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_26
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_27
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_28
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_29
RUN_TEST_STEP !Result=0 5 tdouble_blr  atan2_test \tstdapis\tdouble_blr.ini Section_atan2_test_30

RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  fma_test \tstdapis\tdouble_blr.ini Section_fma_test_16

RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  isfinite_test \tstdapis\tdouble_blr.ini Section_isfinite_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  isnormal_test \tstdapis\tdouble_blr.ini Section_isnormal_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  signbit_test \tstdapis\tdouble_blr.ini Section_signbit_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  ldexp_test \tstdapis\tdouble_blr.ini Section_ldexp_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  round_test \tstdapis\tdouble_blr.ini Section_round_test_12

RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  scalbln_test \tstdapis\tdouble_blr.ini Section_scalbln_test_8

RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  finite_test \tstdapis\tdouble_blr.ini Section_finite_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_11
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_12
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_13
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_14
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_15
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_16
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_17
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_18
RUN_TEST_STEP !Result=0 5 tdouble_blr  drem_test \tstdapis\tdouble_blr.ini Section_drem_test_19

RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  modf_test \tstdapis\tdouble_blr.ini Section_modf_test_10

RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  frexp_test \tstdapis\tdouble_blr.ini Section_frexp_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_test \tstdapis\tdouble_blr.ini Section_remquo_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  remquo_remcheck_test \tstdapis\tdouble_blr.ini Section_remquo_remcheck_test_6

RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  gamma_test \tstdapis\tdouble_blr.ini Section_gamma_test_9

RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_1
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_2
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_3
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_4
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_5
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_6
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_7
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_8
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_9
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_10
RUN_TEST_STEP !Result=0 5 tdouble_blr  lgamma_test \tstdapis\tdouble_blr.ini Section_lgamma_test_11






















