//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tcondinit
LOAD_SUITE tcondinit

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tcondinit TestCond401
RUN_TEST_STEP !Result=0 5 tcondinit TestCond403
//RUN_TEST_STEP !Result=0 5 tcondinit TestCond404
RUN_TEST_STEP !Result=0 5 tcondinit TestCond668
//RUN_TEST_STEP !Result=0 5 tcondinit TestCond670
//RUN_TEST_STEP !Result=0 5 tcondinit TestCond671
//RUN_TEST_STEP !Result=0 5 tcondinit TestCond672
//RUN_TEST_STEP !Result=0 5 tcondinit TestCond673


