//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsemgetvalue
LOAD_SUITE tsemgetvalue

CONSECUTIVE

//RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem313
RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem314
RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem315
RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem316
RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem317
RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem318
//RUN_TEST_STEP !Result=0 5 tsemgetvalue TestSem319



