//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
// Copyright (c) 2006 Symbian Software Ltd.  All rights reserved.
//

CONSECUTIVE
START_TESTCASE OE-001
PRINT --------  Testing open ,Capability set to None
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000000  tfcntl_cap1.exe
LOAD_SUITE tfcntl_cap1
RUN_TEST_STEP   !Result=13 tfcntl_cap1 opensys
END_TESTCASE OE-001


START_TESTCASE OE-002
PRINT --------  Testing open ,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000800  tfcntl_cap2.exe
LOAD_SUITE tfcntl_cap2
RUN_TEST_STEP  tfcntl_cap2 opensys
END_TESTCASE OE-002

START_TESTCASE OE-003
PRINT --------  Testing creat ,Capability set to None
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000000  tfcntl_cap3.exe
LOAD_SUITE tfcntl_cap3
RUN_TEST_STEP !Result=13 tfcntl_cap3 creatsys
END_TESTCASE OE-003

START_TESTCASE OE-004
PRINT --------  Testing creat ,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000800  tfcntl_cap4.exe
LOAD_SUITE tfcntl_cap4
RUN_TEST_STEP !Result=13 tfcntl_cap4 creatsys
END_TESTCASE OE-004


START_TESTCASE OE-005
PRINT --------  Testing open ,Capability set to None
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000000  tfcntl_cap5.exe
LOAD_SUITE tfcntl_cap5
RUN_TEST_STEP   !Result=13 tfcntl_cap5 openprivate
END_TESTCASE OE-005


START_TESTCASE OE-006
PRINT --------  Testing open ,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000800  tfcntl_cap6.exe
LOAD_SUITE tfcntl_cap6
RUN_TEST_STEP  tfcntl_cap6 openprivate
END_TESTCASE OE-006

START_TESTCASE OE-007
PRINT --------  Testing creat ,Capability set to None
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000000  tfcntl_cap7.exe
LOAD_SUITE tfcntl_cap7
RUN_TEST_STEP !Result=13 tfcntl_cap7 creatprivate
END_TESTCASE OE-007

START_TESTCASE OE-008
PRINT --------  Testing creat ,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tfcntlcap.exe 000800  tfcntl_cap8.exe
LOAD_SUITE tfcntl_cap8
RUN_TEST_STEP !Result=13 tfcntl_cap8 creatprivate
END_TESTCASE OE-008