//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// setup-BTSDP-PublicApi.script
//
// Copyright (c) 2006 Symbian Software Ltd. All rights reserved.
//
// Copies files from rom (or simulated rom in case of emulator) to ${SYSDRIVE} to make
// it easier to manually run tests from ${SYSDRIVE}
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS MkDir		${SYSDRIVE}\bluetooth\sdp\

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.tcs


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.tcs


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.tcs


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.tcs

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.script		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.script

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.tcs		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.tcs



RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Active-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Passive-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Agent-PublicApi-Unconnected.ini


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Active-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Database-PublicApi-Passive-Slave.ini


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Active-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Passive-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-Lists-PublicApi-Unconnected.ini


RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Active-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Master.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Passive-Slave.ini

RUN_UTILS CopyFile	z:\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.ini		${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\BTSDP-SearchPattern-PublicApi-Unconnected.ini


RUN_UTILS CopyFile	z:\bluetooth\sdp\testdata.txt		${SYSDRIVE}\bluetooth\sdp\testdata.txt
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\testdata.txt

RUN_UTILS CopyFile	z:\bluetooth\sdp\UccControlChannelConfig.ini		${SYSDRIVE}\bluetooth\sdp\UccControlChannelConfig.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\sdp\UccControlChannelConfig.ini
