//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
///////////////////////////////////////////////////////////////////////////////
// setup-BT-SOCK-ADDR-PublicApi.script
//
// Copyright (c) 2006-2008 Symbian Software Ltd. All rights reserved.
//
// Copies files from rom (or simulated rom in case of emulator) to ${SYSDRIVE} to make
// it easier to manually run tests from ${SYSDRIVE}
///////////////////////////////////////////////////////////////////////////////

RUN_UTILS MkDir		${SYSDRIVE}\bluetooth\

RUN_UTILS CopyFile	z:\bluetooth\BT-SOCK-ADDR-PublicApi.script	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.script
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.script

RUN_UTILS CopyFile	z:\bluetooth\BT-SOCK-ADDR-PublicApi.tcs	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.tcs
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.tcs

RUN_UTILS CopyFile	z:\bluetooth\BT-SOCK-ADDR-PublicApi.ini		${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.ini
RUN_UTILS MakeReadWrite	${SYSDRIVE}\bluetooth\BT-SOCK-ADDR-PublicApi.ini
