//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tcondsignal
LOAD_SUITE tcondsignal

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tcondsignal TestCond439
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond440
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond441
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond442
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond443
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond444
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond445
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond678
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond679
RUN_TEST_STEP !Result=0 5 tcondsignal TestCond680


