//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tpthreadonce
LOAD_SUITE tpthreadonce

CONSECUTIVE
//tpthreadonce
RUN_TEST_STEP !Result=0 5 tpthreadonce TestFramework
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce1682 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce324 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce325 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce326 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce327 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce328 
RUN_TEST_STEP !Result=0 5 tpthreadonce TestOnce329 
