//
// Copyright (c) 2006 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsemtrywait
LOAD_SUITE tsemtrywait

CONSECUTIVE

//RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem388
RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem389
RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem390
RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem391
RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem392
RUN_TEST_STEP !Result=0 5 tsemtrywait TestSem700


